---
- name: Reuse common code
  include_tasks: "{{ playbook_dir }}/../common/config_apply.yml"

- meta: end_play
  when: (allorderers | default([]) | length == 0) or (allpeers | default([]) | length == 0)
